### ISSUE TITLE
Allow to run flow on windows

### ISSUE THREAD

**Issue by MoOx** [rtorr/vscode-flow#1]
Not sure if the message in the banner is really blocking something (it seems it's not, if you define a flow path in the config), but currently, [flow can work](https://github.com/facebook/flow/issues/6#issuecomment-228688828) on windows (even if it's not official yet).
I successfully ran flow by hand after building it myself. It would be nice if this plugin can work (I am new to VS code and I am just setting up this for some collegues that use Windows + VS Code).

Currently I am getting an issue `Tail.open_in_opt: Couldn't open file [2016-07-01 08:04:57] Initializing Server (This might take some time)`. I tried to restart vs code, but the message does not change (especially the time, which seems wrong). Any idea?

**Comment by rtorr** [comment]
There are a few bugs right now that can be related to this. When I have time next week (maybe), I will test running this on Windows. In the mean time, you can see how paths are set up and flow is started here https://github.com/rtorr/vscode-flow/blob/master/src/extension.ts . Though I don't have much time to dig in, I would probably have time for feedback or pull requests if you have questions.

**Comment by kumarharsh** [comment]
+1. I also tried making a folder in the extension's `flow` directory akin to the osx and linux directory, complete with a working `flow.exe` (by @MoOx) and a `flow.js` file. It throws the error mentioned earlier, but it's not an error. But after some time, a major error is thrown: `Error from the extension host: channel closed` and then `Extension host terminated unexpectedly. Please reload the window to recover.`

**Comment by rtorr** [comment]
The community is going in a different direction. To follow look at https://github.com/flowtype/flow-for-vscode/pull/19#discussion_r70846888

**Comment by kumarharsh** [comment]
Thanks for the link, it was an interesting read, although I couldn't find anything directly related to running flow on windows. The repo also has just 1 closed issue about supporting windows right now. Does supporting vscode automatically guarantee support for vscode on windows? I'm sorry if this question sounds simple, but I'm still understanding the innards of vscode.

**Comment by rtorr** [comment]
@kumarharsh So this is just about the vscode extension, not Windows support.

The flow team is working on flow support, so I think once that is done, the extension I liked should work or will work once parched.

This link mentions Windows support https://github.com/facebook/flow/releases/tag/v0.29.0 being worked on
