### ISSUE TITLE
More updates via xanf

### ISSUE THREAD

**Issue by rtorr** [rtorr/vscode-flow#13]
@xanf I merged your other PRs, but want to track these items also. Reference this with your PRs. Also, thanks for the awesome work!

@rtorr Actually i'm thinking of closing this three pull requests and merging into one. After playing a night with code it seems we need a bit more changes everythere:

- [x] remove no-auto-start - flow seems to handle pretty well autostarting
- [x] tune helper so we will not raise error output if flow ended with code 0 - that will prevent spamming things like "flow server is still starting..."
- [ ] switch to [cross-spawn](https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=cross-spawn%20npm) instead of spawn - i had problems with files with spaces on windows

- [x] ~~remove license from FB - i asked my facebook colleagues (I'm not working for facebook) - they say there is nothing which should be licensed here - it's just boilerplate extension code and flow invocation~~ (done)

If you're fine with it - i will open one big pull with all that changes. Actually I really like simple `flow` invocation over dark nuclide magic

**Comment by xanf** [comment]
@rtorr Sorry, missed thisi issue, so first two are #15
