### ISSUE TITLE
Unhandled exception: End_of_file

### ISSUE THREAD

**Issue by tomitrescak** [rtorr/vscode-flow#17]
Hi, Flow keeps crashing quite often with following exception: `Unhandled exception: End_of_file`.

If you tell me where can I search for log files I'll be more then glad to pot them here.
I'm using Mac OS.X. El Capitan and latest vscode and latest plugin version.

[edit] I can't confirm, but it seems that the problem was when there were no new-line characters at the end of the file.

**Comment by rtorr** [comment]
Can you post a file where this will happen? Gist?

**Comment by tomitrescak** [comment]
Hi, thanks for a rapid feedback:

Hi, not sure what is going on, but following always results into End_of_file error.

```js
// file one has following import
import mf from '../configs/i18n'; 
```

i18n file

```js
// this is the i18n file
const mf = (key: string, params?: Object): string => {
  return key;
};  

export default mf; 
```

**Comment by rtorr** [comment]
I cannot seem to reproduce :(

Can you maybe create a repo that i can clone exactly what you have?

**Comment by tomitrescak** [comment]
@rtorr I now have a public repo which I will be able to share, but of course the error now disappeared. Once I'll safely be able to reproduce I'll reopen.
