### ISSUE TITLE
Go to definition and peek definition does not work

### ISSUE THREAD

**Issue by tomitrescak** [rtorr/vscode-flow#18]
Hi, thanks for the amazing package! I have a small issue when go to definition and peek definition does not work. It works only on the definition in current file, yet, when I try to go to definition of a function from the imported type it does not work. Yet, the function is correctly detected by the flow plugin.

**Comment by rtorr** [comment]
Thanks for reporting. Will look. This extension is still new and not fully done yet.

**Comment by rtorr** [comment]
This project is now depreicated
