### ISSUE TITLE
Type error messages for imported types are reversed

### ISSUE THREAD

**Issue by PaulSilas** [rtorr/vscode-flow#19]
Great start to a much needed extension for VS Code. I'm using this on Windows but found an issue where the error messages shown for imported types seem to be reversed. The attached screenshot illustrates the issue I'm seeing. I would expect that the messages I see when I hover over the red underline in the type definition file is what I would see when I hover over its usage in test.js.

![image](https://cloud.githubusercontent.com/assets/10040396/18029771/7bbb4894-6c6f-11e6-8b37-80927117cc55.png)

**Comment by rtorr** [comment]
This project is now depreicated
