### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by aikeru** [rtorr/vscode-flow#23]
Hi there. I noticed today while attempting to install flow support for VSCode there are 3 options that pop up (vscode-flow, vscode-flow-ide, and Flow Language Support).

This seems close to the vscode-flow-ide project, but that one seems to have more recent commits.

Might this mean that this project is deprecated somehow? Just looking for clarity amongst the choices available. Thank you!

**Comment by rtorr** [comment]
Yep. This project was a nice temporary fix. Use the official one.

**Comment by aikeru** [comment]
Hey @rtorr thanks for your response and also for this extension!
For the sake of others who have similar questions - might it be a good idea for this package to also be marked deprecated somehow from the VS Code marketplace?

**Comment by rtorr** [comment]
Yep! When I have time :D
