### ISSUE TITLE
Plugin highlights all object keys as flow types but does not highlight actual types

### ISSUE THREAD

**Issue by AndrewRayCode** [rtorr/vscode-flow#24]
Incorrect highlighting of any object keys:

![screen shot 2017-03-05 at 10 09 22 pm](https://cloud.githubusercontent.com/assets/79215/23598605/6a0dddb6-01f0-11e7-818d-ad8db01fd7ff.png)

Including named destructuring:

![screen shot 2017-03-05 at 10 09 43 pm](https://cloud.githubusercontent.com/assets/79215/23598619/7804242a-01f0-11e7-80dc-7ecd196a1f2b.png)

Does not highlight actual flow types:

![screen shot 2017-03-05 at 10 10 16 pm](https://cloud.githubusercontent.com/assets/79215/23598635/97e167c6-01f0-11e7-991d-8465afa3ae95.png)

![screen shot 2017-03-05 at 10 10 31 pm](https://cloud.githubusercontent.com/assets/79215/23598639/9d8d1058-01f0-11e7-9646-829f0e6eb375.png)

This plugin actually *removes* highlighting from flow types. Without this plugin, `type` is highlighted:

![screen shot 2017-03-05 at 10 11 36 pm](https://cloud.githubusercontent.com/assets/79215/23598663/bffe9760-01f0-11e7-9a21-60284d03ffeb.png)

**Comment by rtorr** [comment]
This project is deprecated. I'll update the readme soon
