### ISSUE TITLE
Bug: `A:A:A:A:...` in .js file locks up editor

### ISSUE THREAD

**Issue by voltrevo** [rtorr/vscode-flow#25]
- VSCode Version: 1.10.2
- vscode-flow Version: 276.3.0
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Open new file
2. Save with .js extension
3. Type `A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:`

Visual studio code locks up for me when I do this. Keep repeating the A:A:A:... pattern as much as necessary, it feels like something has exponential time complexity as this is repeated. This also happens if the string is quoted, which is strange for both theories though.

I originally filed this with VSCode itself here https://github.com/Microsoft/vscode/issues/23510. @kaiwood pointed me to the `--disable-extensions` flag, which lead me to discover that this only happens when vscode-flow is enabled.

**Comment by rtorr** [comment]
This project is deprecated and removed from the extensions marketplace

https://github.com/rtorr/vscode-flow#deprecated-please-use-httpsgithubcomflowtypeflow-for-vscode
