### ISSUE TITLE
The flow server's version didn't match the client's, so it exited.

### ISSUE THREAD

**Issue by nmn** [rtorr/vscode-flow#4]
I've tried this extension a few times, and Ive always had the same issue
`The flow server's version didn't match the client's, so it exited.`

I have flow installed, and available on the path. It works fine with Nuclide and `linter-flow` in atom.

It also works fine with `autocomplete-flow` for atom.

Tried investigating so I could give you a PR instead of an issue, but I've not been able to figure out what's going on here.

My best guess seems to be that the extension hard-codes the flow version which makes it break unless the flow version on my computer matches that of the extension. I would say this is not a good pattern to follow as flow gets updated very regularly, and usually there are almost no changes to the cli and the API.

The extension should work no matter what version of flow is installed on the computer.

**Comment by rtorr** [comment]
I thought this may come up. I will try and patch soon. Thanks

**Comment by rtorr** [comment]
@nmn as a temporary fix, can you put the flowpath in your projects `.vscode/settings.json` as 

```
"flow": "path/to/flow"
```

That you want to use for that project?

**Comment by nmn** [comment]
@rtorr That didn't work at all :(

I just see absolutely nothing now.

**Comment by navarrorc** [comment]
Don't know if this helps but my path in the settings.json is as follows:
"flow.path": "C:\\Users\\[User]\\AppData\\Roaming\\npm\\node_modules\\flow-bin\\vendor\\flow.exe"

Using Windows and it's working.
![flow_vscode_windows](https://cloud.githubusercontent.com/assets/215220/17459816/6aae42b0-5c0f-11e6-8a9a-f21a8c6893ce.PNG)

**Comment by rtorr** [comment]
@nmn can you try again with the above example?

**Comment by rtorr** [comment]
There has also been a few changes if you are on the latest version https://github.com/rtorr/vscode-flow/blob/master/README.md#setup

**Comment by rtorr** [comment]
Probably should change it to only see if flow.path exists

**Comment by rtorr** [comment]
Now you only need flow path in your `settings.json`.

Please reference https://github.com/rtorr/vscode-flow/blob/master/README.md#setup.

Closing.
